# -*- coding: utf-8 -*-
"""qr_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EJXjunyEcDRLfwfhSZ9EM2mqR5fJxlz3
"""

!pip install qrcode[pil] pyzbar opencv-python numpy

#@title **QR Code Generator**
import qrcode
from PIL import Image
from IPython.display import display

# Set your target URL directly
data = "https://www.freecodecamp.org/news/python-projects-for-beginners/#heading-qr-code-encoder-decoder-python-project"

# Create QR code
qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_H,
    box_size=10,
    border=4,
)

qr.add_data(data)
qr.make(fit=True)

# Generate image
img = qr.make_image(fill_color="black", back_color="white")

# Save and display
img.save("freecodecamp_qr.png")
print("✅ QR Code generated successfully!\nScan this code to visit:")
print(data + "\n")
display(img)